version: "3"
services:
  dba-oracle:
    build: .
    container_name: dba-oracle
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=dba_oracle
      - ORACLE_PDB=dba_oracle
    volumes:
      - dba-oracle-data:/opt/oracle/oradata

volumes:
  dba-oracle-data: {}
